import type { Metadata } from "next";
import { CormorantGaramondRegular, Inter } from "@/styles/fonts";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Kristina Kostova Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${Inter.variable} ${CormorantGaramondRegular.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
